### PR TITLE
Use shape id to name layers

### PR DESCRIPTION
**Pull request by ephread**
Hi! Thanks a lot for maintaining this lightweight SVG library, it's clean and really easy to use. 👏

Since I needed to discriminate paths based on their `id`, I have made a small change which will name the layers using the original value of `id`.

Is that something you'd consider adding to the main project?

Let me know if you need me to make some changes to the PR.

### CODE REVIEW

**Comment by onmyway133** [comment]
@ephread Hi, thanks for the PR, I like it 👍 
One thing is that you made changes to gitignore and moving svg files from Resources for Supporting folders, is that because of "Revamp project architecture to fix App Store framework submission" ?

**Comment by ephread** [comment]
> Hi, thanks for the PR, I like it 👍

Awesome!

> One thing is that you made changes to gitignore and moving svg files from Resources for Supporting folders, is that because of "Revamp project architecture to fix App Store framework submission" ?
Merge state

I'm so sorry. I forgot about this PR and updated the master branch with changes that have nothing to do with the original PR. I'll open another issue to talk about the Framework-related problem.

Anyhow, the reorganization wasn't intended to be merged back. That would be terribly offhand to make such PR without prior discussion. Let me move the second commit out of the master branch.

**Comment by onmyway133** [comment]
@ephread I merged it 👍 
Sorry that it takes long to react to this PR (somehow I don't get notifications about this)

**Comment by ephread** [comment]
@onmyway133 no worries, thanks for merging!

**Pull request merged**
